postgres_enums_lib: oa-enums2
postgres_enums_dir: ./purs/lib/generated/
shared_graphql_enums_lib: oa-gql-enums
shared_graphql_enums_dir: ./purs/lib/generated/
schema_libs_prefix: oa-gql-schema-
schema_libs_dir: ./purs/lib/generated/