postgres_enums_lib: oa-enums-postgres
postgres_enums_dir: ./purs-projects/lib/generated-gql-external/
shared_graphql_enums_lib: oa-gql-external-
shared_graphql_enums_dir: ./purs-projects/lib/generated-gql-external/
schema_libs_prefix: oa-gql-external-schema-
schema_libs_dir: ./purs-projects/lib/generated-gql-external/
enums_package_name: gql-enums